services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    env_file:
      - .env.production

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    depends_on:
      - mongo
      - redis
    env_file:
      - .env.production


volumes:
  mongo_data:
  redis_data:

